#!/bin/bash

function run_test
{
# need to handle different languages   
  npm run lint
  if [ $? != '0' ]; then
    exit 1
  fi 
}

case "${1}" in 
    --about )
        echo "Prevent committing if lint errors"
        ;;
   * )
        run_test "$@" 
    ;;
esac





