#!/bin/bash

function run_test
{
  # todo need to handle different languages   
  if [ -f .eslintrc ]; then
    npm run lint
    if [ $? != '0' ]; then
      exit 1
    fi 
  fi
}

case "${1}" in 
    --about )
        echo "Prevent committing if lint errors"
        ;;
   * )
        run_test "$@" 
    ;;
esac





