#!/bin/bash

function run_test
{
  npm test
  if [ $? != '0' ]; then
    exit 1
  fi
}

case "${1}" in 
    --about )
        echo "Prevent pushing if tests fails"
        ;;
   * )
        run_test "$@" 
    ;;
esac

